# Generated by Django 6.0.5 on 2026-05-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_refreshtoken_is_sudo_mode_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email_confirmation_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
