location / {
    set $frontend http://frontend-main-app:3000;
    proxy_pass $frontend;
    include /etc/nginx/conf.d/proxy_params.conf;

    # Next.js uses WebSockets for HMR in dev; harmless in prod.
    proxy_set_header Upgrade    $http_upgrade;
    proxy_set_header Connection "upgrade";
}
