location /iam/v1/ {
    limit_req zone=microservice_iam_limit burst=5 nodelay;

    proxy_pass http://microservice_iam;
    include /etc/nginx/conf.d/proxy_params.conf;
}

# Only local network
location /iam/ {
    # Container itself
    allow 127.0.0.1;

    # Allow docker network
    allow 172.16.0.0/12;

    # Internal network
    allow 192.168.1.0/16;
    allow 10.0.0.0/8;

    # Deny everyone else
    deny all;

    proxy_pass http://microservice_iam;
    include /etc/nginx/conf.d/proxy_params.conf;
}
