location /api/iam/v1/ {
    limit_req zone=microservice_iam_limit burst=5 nodelay;

    set $iam http://microservice_iam:8000;
    proxy_pass $iam;
    include /etc/nginx/conf.d/proxy_params.conf;
}

# --- Only local network ---
location /api/iam/v1/internal/ {
    allow 127.0.0.1;
    allow 172.16.0.0/12;
    allow 192.168.0.0/16;
    allow 10.0.0.0/8;
    #deny all;

    set $iam http://microservice_iam:8000;
    proxy_pass $iam;
    include /etc/nginx/conf.d/proxy_params.conf;
}

location /api/iam/admin/ {
    allow 127.0.0.1;
    allow 172.16.0.0/12;
    allow 192.168.0.0/16;
    allow 10.0.0.0/8;
    #deny all;

    set $iam http://microservice_iam:8000;
    proxy_pass $iam;
    include /etc/nginx/conf.d/proxy_params.conf;
}

# END --- Only local network ---
