name: "Chore"
description: "For maintenance or cleanup tasks"
title: "[Chore][Frontend|Backend|General] <short subject>"
labels: ["chore"]
body:
  - type: input
    id: subject
    attributes:
      label: "Chore Summary"
      description: "Briefly describe what needs to be done."
      placeholder: "Example: Clean up unused components in the UI"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "Explain what needs maintenance or cleanup, and why it's needed."
      placeholder: "Describe steps, affected areas, or follow-up tasks."
