name: "Docs"
description: "For improving or adding documentation"
title: "[Docs][Frontend|Backend|General] <short subject>"
labels: ["documentation"]
body:
  - type: input
    id: subject
    attributes:
      label: "Documentation Summary"
      description: "Briefly describe what needs to be documented or updated."
      placeholder: "Example: Add README section for setting up Prettier"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "Explain what documentation is missing, unclear, or needs improvement."
      placeholder: "Include file paths, specific topics, or examples of missing info."
