name: "Feature"
description: "For proposing a new feature or improvement"
title: "[Feature][Frontend|Backend|General] <short subject>"
labels: ["feature"]
body:
  - type: input
    id: subject
    attributes:
      label: "Feature Summary"
      description: "Briefly describe the new feature or improvement."
      placeholder: "Example: Add seat reservation visualization in movie room"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Explain what this feature should do and why it’s needed."
      placeholder: "Describe functionality, goals, user impact, or examples."
      validations:
        required: true
