name: "Lint PR Title"

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  check-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Lint PR Title
        id: lint_pr_title
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            chore
            docs
            refactor
            test
            style
            research
          headerPattern: '^\[(?<type>feat|fix|chore|docs|refactor|test|style|research)]\[(?<scope>frontend|backend|devops|ux|general)] (?<subject>.+)$'
          headerPatternCorrespondence: type, scope, subject
          subjectPattern: '^[a-zA-Z].*'

      - name: Comment on invalid PR title
        if: always() && steps.lint_pr_title.outputs.error_message != null
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          message: |
            📝 **Heads up!** Your PR title doesn’t match the expected format:

            `[type][lane] subject`

            Example valid titles:
            - `[feat][frontend] add movie room ui`
            - `[fix][backend] prevent seat overbooking`
            - `[docs][general] update readme instructions`

            Please update the PR title so it follows this format. Thanks! 🙂

      - name: Remove comment if PR title fixed
        if: steps.lint_pr_title.outputs.error_message == null
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
